name: entry
description: Make your widgets come to life â€“ Entry lets you simply animate a widget into a visible state. One widget to animate the opacity, scale, position and angle.
version: 1.0.2
homepage: "https://github.com/MickaelHrndz/entry"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  simple_animations: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: 'Named constructors'
    path: example/assets/entry.gif
  - description: 'Combining Entry widgets'
    path: example/assets/combined.gif
  - description: 'Staggered animations'
    path: example/assets/staggered.gif
  - description: 'Randomized animations'
    path: example/assets/randomized.gif